.TH "GDIREL" "1" "March 2024" "Gdirel v1.0.0" "User Commands"
.SH NAME
Gdirel - Get distribution information, like lsb_release
.SH DESCRIPTION
Low requirements utility tool that provides basic information about distribution, is like lsb_release.
.SH USAGE
\fB\-k\fR
displays current kernel release.
.HP
.TP
\fB\-o\fR
print distribution name.
.HP
.TP
\fB\-m\fR
print current/native package manager name.
.HP
.TP
\fB\-n\fR
how many packages are installed with current/native package manager.
.HP
.TP
\fB\-p\fR
print processor model.
.HP
.TP
\fB\-c\fR
print the cpu have how many cores.
.HP
.TP
\fB\-a\fR
print all informations above.
.TP
\fB\-v\fR
print with verbose \"add header like (any: x)\".
.HP
.TP
\fB\-h\fR
print this screen.
.SH INFO
Pull requests are open: https://github.com/lazypwny751/gdirel